export const PROMPT_OPTIONS = [
  "Describe a day at school",
  "Describe a vacation",
  "Describe a sick day",
  "Describe a meal",
  "Describe a weekend",
  "Describe a cocktail",
  "Describe a smoothie",
  "Describe a hike",
  "Describe an animal",
  "Describe a teacher",
  "Describe a boss",
  "Describe a summer camp experience",
  "Describe a piece of furniture",
  "Describe a friend",
  "Describe a roommate",
  "Describe a dessert",
  "Describe a brunch",
  "Describe a stuffed animal",
  "Describe a painting",
  "Describe a flower",
  "Describe a pancake",
  "Describe a bike",
  "Describe a movie",
  "Describe a song",
  "Describe a date",
  "Describe meeting a new person",
  "Describe buying something from a vending machine",
  "Describe a supermarket experience",
  "Describe telling your family news",
];
